config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /ru|en|tm/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    devise_for :users
    #get 'home/index'
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    root 'home#index'

    resources :projects
    # Defines the root path route ("/")
    # root "articles#index"
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/header.rb
class Header < ApplicationRecord
  has_one_attached :logo

  #validates :logo, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many_attached :images
end

app/models/slider.rb
class Slider < ApplicationRecord
  has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def login
    @login || self.username || self.email
  end

  # app/models/user.rb

  def self.find_for_database_authentication(warden_conditions)
   conditions = warden_conditions.dup
   if (login = conditions.delete(:login))
     where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
   elsif conditions.has_key?(:username) || conditions.has_key?(:email)
     where(conditions.to_h).first
   end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale, :navbar_links

  private

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end

  def extract_locale
    parsed_locale = params[:locale]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def navbar_links
    Header.all.each { |header| @header = header }

    @type = @header.type_ru if params[:locale] != true and params[:locale] != 'en' and params[:locale] != 'tm' and params[:locale] != 'ru'
    @type = @header.type_ru if params[:locale] == 'ru'
    @type = @header.type_en if params[:locale] == 'en'
    @type = @header.type_tm if params[:locale] == 'tm'
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #@headers = Header.all

      @sliders = Slider.all


  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/_footer.html.erb
<footer class="footer">
  <div class="container-fluid px-lg-5">
    <div class="row">
      <div class="col-md-9 py-5">
        <div class="row">
          <div class="col-md-4 mb-md-0 mb-4">
            <h2 class="footer-heading">About us</h2>
            <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
            <ul class="ftco-footer-social p-0">
              <li class="ftco-animate"><a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><span class="ion-logo-twitter"></span></a></li>
              <li class="ftco-animate"><a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><span class="ion-logo-facebook"></span></a></li>
              <li class="ftco-animate"><a href="#" data-toggle="tooltip" data-placement="top" title="Instagram"><span class="ion-logo-instagram"></span></a></li>
            </ul>
          </div>
          <div class="col-md-8">
            <div class="row justify-content-center">
              <div class="col-md-12 col-lg-10">
                <div class="row">
                  <div class="col-md-4 mb-md-0 mb-4">
                    <h2 class="footer-heading">Services</h2>
                    <ul class="list-unstyled">
                      <li><a href="#" class="py-1 d-block">Construction</a></li>
                      <li><a href="#" class="py-1 d-block">House Renovation</a></li>
                      <li><a href="#" class="py-1 d-block">Painting</a></li>
                      <li><a href="#" class="py-1 d-block">Arhictecture Design</a></li>
                    </ul>
                  </div>
                  <div class="col-md-4 mb-md-0 mb-4">
                    <h2 class="footer-heading">About</h2>
                    <ul class="list-unstyled">
                      <li><a href="#" class="py-1 d-block">Staff</a></li>
                      <li><a href="#" class="py-1 d-block">Team</a></li>
                      <li><a href="#" class="py-1 d-block">Careers</a></li>
                      <li><a href="#" class="py-1 d-block">Blog</a></li>
                    </ul>
                  </div>
                  <div class="col-md-4 mb-md-0 mb-4">
                    <h2 class="footer-heading">Resources</h2>
                    <ul class="list-unstyled">
                      <li><a href="#" class="py-1 d-block">Security</a></li>
                      <li><a href="#" class="py-1 d-block">Global</a></li>
                      <li><a href="#" class="py-1 d-block">Charts</a></li>
                      <li><a href="#" class="py-1 d-block">Privacy</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row mt-md-5">
          <center><%= Time.now.year %></center>
        </div>
      </div>
      <div class="col-md-3 py-md-5 py-4 aside-stretch-right pl-lg-5">
        <h2 class="footer-heading">Request A Quote</h2>
        <form action="#" class="contact-form">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Your Name">
          </div>
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Your Email">
          </div>
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Subject">
          </div>
          <div class="form-group">
            <textarea name="" id="" cols="30" rows="3" class="form-control" placeholder="Message"></textarea>
          </div>
          <div class="form-group">
            <button type="submit" class="form-control submit px-3">Send</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</footer>

app/views/home/_lang.html.erb
<div class="modal fade" id="lang" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <div class="row">
          <div class="col-3">
            <%= link_to url_for(locale: :ru), :class => "navi", :style => "text-decoration: none;" do %>
              <%= image_tag "/assets/ru.png", :class => "flag" %>
              RUS
            <% end %>
          </div>
          <div class="col-3">
            <%= link_to url_for(locale: :en), :class => "navi", :style => "text-decoration: none;" do %>
              <%= image_tag "/assets/en.png", :class => "flag" %>
              ENG
            <% end %>
          </div>
          <div class="col-3">
            <%= link_to url_for(locale: :tm), :class => "navi", :style => "text-decoration: none;" do %>
              <%= image_tag "/assets/tm.png", :class => "flag" %>
              TKM
            <% end %>
          </div>
          <div class="col-3">
            <h3 style="font-family: bankgothic; font-weight: 900; font-size: 15px;">
              BURKUT
            </h3>
          </div>
        </div>




        <center>
      </div>
    </div>
  </div>
</div>

app/views/home/_navbar.html.erb
<div class="container pt-5">
  <div class="row justify-content-between">
    <div class="col">
      <%= link_to root_path, class:"navbar-brand"  do %>
        <b style="font-family: bankgothic; font-weight: 900; font-size: 35px; width: 300px;">BURKUT</b>
        <b style="font-family: bankgothic; font-weight: 900; font-size: 25px; width: 300px;"><span><%= @type.upcase %>.</span></b>
      <% end %>
    </div>
    <div class="col d-flex justify-content-end">
      <div class="social-media">
        <p class="mb-0 d-flex">
          <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-facebook"><i class="sr-only">Facebook</i></span></a>
          <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-twitter"><i class="sr-only">Twitter</i></span></a>
          <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-instagram"><i class="sr-only">Instagram</i></span></a>
          <a href="#" class="d-flex align-items-center justify-content-center" data-bs-target="#lang" data-bs-toggle="modal">
            <span class="fa fa-dribbble">
              <i class="sr-only">

              </i>
            </span>
          </a>
        </p>
      </div>
    </div>
  </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light sticky-top" id="ftco-navbar">
  <div class="container">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="fa fa-bars"></span> Menu
    </button>
    <form action="#" class="searchform order-lg-last">
      <div class="form-group d-flex">
        <input type="text" class="form-control pl-3" placeholder="Search">
        <button type="submit" placeholder="" class="form-control search"><span class="fa fa-search"></span></button>
      </div>
    </form>
    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active"><%= link_to t('navbar.home').upcase, root_path, class:"nav-link"%></li>
        <li class="nav-item"><%= link_to t('navbar.project').upcase, projects_path, class:"nav-link"%></li>
        <li class="nav-item"><a href="team.html" class="nav-link">Our team</a></li>
        <li class="nav-item"><a href="project.html" class="nav-link">Project</a></li>
        <li class="nav-item"><a href="blog.html" class="nav-link">Blog</a></li>
        <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/_section1.html.erb
<section class="ftco-section ftco-no-pt ftco-no-pb">
  <div class="container">
    <div class="row">
      <div class="col-md-3 d-flex services align-self-stretch p-4 py-md-5 ftco-animate">
        <div class="media block-6 d-block text-center pt-md-4">
          <div class="icon d-flex justify-content-center align-items-center">
            <span class="flaticon-hook"></span>
          </div>
          <div class="media-body p-2 mt-3">
            <h3 class="heading">Construction</h3>
            <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
          </div>
        </div>
      </div>
      <div class="col-md-3 d-flex services align-self-stretch p-4 py-md-5 ftco-animate">
        <div class="media block-6 d-block text-center pt-md-4">
          <div class="icon d-flex justify-content-center align-items-center">
            <span class="flaticon-skyline"></span>
          </div>
          <div class="media-body p-2 mt-3">
            <h3 class="heading">House Renovation</h3>
            <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
          </div>
        </div>
      </div>
      <div class="col-md-3 d-flex services align-self-stretch p-4 py-md-5 ftco-animate">
        <div class="media block-6 d-block text-center pt-md-4">
          <div class="icon d-flex justify-content-center align-items-center">
            <span class="flaticon-stairs"></span>
          </div>
          <div class="media-body p-2 mt-3">
            <h3 class="heading">Painting</h3>
            <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
          </div>
        </div>
      </div>
      <div class="col-md-3 d-flex services align-self-stretch p-4 py-md-5 ftco-animate">
        <div class="media block-6 d-block text-center pt-md-4">
          <div class="icon d-flex justify-content-center align-items-center">
            <span class="flaticon-home"></span>
          </div>
          <div class="media-body p-2 mt-3">
            <h3 class="heading">Architecture Design</h3>
            <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row no-gutters">
      <div class="col-md-12 col-lg-4 services-2 p-4 py-5 d-flex ftco-animate">
        <div class="py-3 d-flex">
          <div class="icon">
            <span class="flaticon-engineer"></span>
          </div>
          <div class="text">
            <h3>Expert &amp; Professional</h3>
            <p class="mb-0">Separated they live in. A small river named Duden flows</p>
          </div>
        </div>
      </div>
      <div class="col-md-12 col-lg-4 services-2 p-4 py-5 d-flex ftco-animate">
        <div class="py-3 d-flex">
          <div class="icon">
            <span class="flaticon-engineer-1"></span>
          </div>
          <div class="text">
            <h3>High Quality Work</h3>
            <p class="mb-0">Separated they live in. A small river named Duden flows</p>
          </div>
        </div>
      </div>
      <div class="col-md-12 col-lg-4 services-2 p-4 py-5 d-flex ftco-animate">
        <div class="py-3 d-flex">
          <div class="icon">
            <span class="flaticon-engineer-2"></span>
          </div>
          <div class="text">
            <h3>24/7 Help Support</h3>
            <p class="mb-0">Separated they live in. A small river named Duden flows</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/_section2.html.erb
<section class="ftco-section ftco-no-pt ftco-no-pb">
  <div class="container">
    <div class="row d-flex no-gutters">
      <div class="col-md-6 d-flex">
        <div class="img img-video d-flex align-self-stretch align-items-center justify-content-center justify-content-md-end" style="background-image:url(images/about.jpg);">
          <a href="https://vimeo.com/45830194" class="icon-video popup-vimeo d-flex justify-content-center align-items-center">
            <span class="icon-play"></span>
          </a>
        </div>
      </div>
      <div class="col-md-6 pl-md-5">
        <div class="row justify-content-start py-5">
          <div class="col-md-12 heading-section ftco-animate pl-md-4 py-md-4">
            <span class="subheading">Welcome to Home Builder</span>
            <h2 class="mb-4">We create and turn into reality</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
            <div class="tabulation-2 mt-4">
              <ul class="nav nav-pills nav-fill d-md-flex d-block">
                <li class="nav-item mb-md-0 mb-2">
                  <a class="nav-link active py-2" data-toggle="tab" href="#home1">Our Mission</a>
                </li>
                <li class="nav-item px-lg-2 mb-md-0 mb-2">
                  <a class="nav-link py-2" data-toggle="tab" href="#home2">Our Vision</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link py-2 mb-md-0 mb-2" data-toggle="tab" href="#home3">Our Value</a>
                </li>
              </ul>
              <div class="tab-content bg-light rounded mt-2">
                <div class="tab-pane container p-0 active" id="home1">
                  <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                </div>
                <div class="tab-pane container p-0 fade" id="home2">
                  <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                </div>
                <div class="tab-pane container p-0 fade" id="home3">
                  <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/_section3.html.erb
<section class="ftco-counter" id="section-counter">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
        <div class="block-18 d-flex">
          <div class="text d-flex align-items-center">
            <strong class="number" data-number="50">0</strong>
          </div>
          <div class="text-2">
            <span>Years of <br>Experienced</span>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
        <div class="block-18 d-flex">
          <div class="text d-flex align-items-center">
            <strong class="number" data-number="8500">0</strong>
          </div>
          <div class="text-2">
            <span>Project <br>Done</span>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
        <div class="block-18 d-flex">
          <div class="text d-flex align-items-center">
            <strong class="number" data-number="378">0</strong>
          </div>
          <div class="text-2">
            <span>Professional <br>Expert</span>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
        <div class="block-18 d-flex">
          <div class="text d-flex align-items-center">
            <strong class="number" data-number="1200">0</strong>
          </div>
          <div class="text-2">
            <span>Machineries <br>Equipments</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/_section4.html.erb
<section class="ftco-section ftco-no-pt ftco-no-pb">
  <div class="container-fluid px-md-0">
    <div class="row no-gutters">
      <div class="col-md-4 ftco-animate">
        <div class="work img d-flex align-items-end" style="background-image: url(images/work-1.jpg);">
          <a href="images/work-1.jpg" class="icon image-popup d-flex justify-content-center align-items-center">
            <span class="icon-expand"></span>
          </a>
          <div class="desc w-100 px-4">
            <div class="text w-100 mb-3">
              <span>Building</span>
              <h2><a href="work-single.html">College Health Profession</a></h2>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 ftco-animate">
        <div class="work img d-flex align-items-end" style="background-image: url(images/work-2.jpg);">
          <a href="images/work-2.jpg" class="icon image-popup d-flex justify-content-center align-items-center">
            <span class="icon-expand"></span>
          </a>
          <div class="desc w-100 px-4">
            <div class="text w-100 mb-3">
              <span>Building</span>
              <h2><a href="work-single.html">College Health Profession</a></h2>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 ftco-animate">
        <div class="work img d-flex align-items-end" style="background-image: url(images/work-3.jpg);">
          <a href="images/work-3.jpg" class="icon image-popup d-flex justify-content-center align-items-center">
            <span class="icon-expand"></span>
          </a>
          <div class="desc w-100 px-4">
            <div class="text w-100 mb-3">
              <span>Building</span>
              <h2><a href="work-single.html">College Health Profession</a></h2>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4 ftco-animate">
        <div class="work img d-flex align-items-end" style="background-image: url(images/work-4.jpg);">
          <a href="images/work-4.jpg" class="icon image-popup d-flex justify-content-center align-items-center">
            <span class="icon-expand"></span>
          </a>
          <div class="desc w-100 px-4">
            <div class="text w-100 mb-3">
              <span>Building</span>
              <h2><a href="work-single.html">College Health Profession</a></h2>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 ftco-animate">
        <div class="work img d-flex align-items-end" style="background-image: url(images/work-5.jpg);">
          <a href="images/work-5.jpg" class="icon image-popup d-flex justify-content-center align-items-center">
            <span class="icon-expand"></span>
          </a>
          <div class="desc w-100 px-4">
            <div class="text w-100 mb-3">
              <span>Building</span>
              <h2><a href="work-single.html">College Health Profession</a></h2>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 ftco-animate">
        <div class="work img d-flex align-items-end" style="background-image: url(images/work-6.jpg);">
          <a href="images/work-6.jpg" class="icon image-popup d-flex justify-content-center align-items-center">
            <span class="icon-expand"></span>
          </a>
          <div class="desc w-100 px-4">
            <div class="text w-100 mb-3">
              <span>Building</span>
              <h2><a href="work-single.html">College Health Profession</a></h2>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/_section5.html.erb
<section class="ftco-section testimony-section bg-primary">
  <div class="container">
    <div class="row justify-content-center mb-5">
      <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
        <span class="subheading">Testimonial</span>
        <h2 class="mb-4">Happy Clients</h2>
      </div>
    </div>
    <div class="row ftco-animate">
      <div class="col-md-12">
        <div class="carousel-testimony owl-carousel ftco-owl">
          <div class="item">
            <div class="testimony-wrap py-4">
              <div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-quote-left"></span></div>
              <div class="text">
                <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                <div class="d-flex align-items-center">
                  <div class="user-img" style="background-image: url(images/person_1.jpg)"></div>
                  <div class="pl-3">
                    <p class="name">Roger Scott</p>
                    <span class="position">Marketing Manager</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="testimony-wrap py-4">
              <div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-quote-left"></span></div>
              <div class="text">
                <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                <div class="d-flex align-items-center">
                  <div class="user-img" style="background-image: url(images/person_2.jpg)"></div>
                  <div class="pl-3">
                    <p class="name">Roger Scott</p>
                    <span class="position">Marketing Manager</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="testimony-wrap py-4">
              <div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-quote-left"></span></div>
              <div class="text">
                <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                <div class="d-flex align-items-center">
                  <div class="user-img" style="background-image: url(images/person_3.jpg)"></div>
                  <div class="pl-3">
                    <p class="name">Roger Scott</p>
                    <span class="position">Marketing Manager</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="testimony-wrap py-4">
              <div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-quote-left"></span></div>
              <div class="text">
                <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                <div class="d-flex align-items-center">
                  <div class="user-img" style="background-image: url(images/person_1.jpg)"></div>
                  <div class="pl-3">
                    <p class="name">Roger Scott</p>
                    <span class="position">Marketing Manager</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="testimony-wrap py-4">
              <div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-quote-left"></span></div>
              <div class="text">
                <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                <div class="d-flex align-items-center">
                  <div class="user-img" style="background-image: url(images/person_2.jpg)"></div>
                  <div class="pl-3">
                    <p class="name">Roger Scott</p>
                    <span class="position">Marketing Manager</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/_section7.html.erb
<section class="ftco-section ftco-no-pb ftco-no-pt mb-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="bg-primary w-100 rounded px-md-0 px-4">
          <div class="row d-flex justify-content-center">
            <div class="col-lg-8 py-4">
              <div class="row">
                <div class="col-md-6 d-flex align-items-center">
                  <h2 class="mb-0" style="color:white; font-size: 24px;">Subcribe to our Newsletter</h2>
                </div>
                <div class="col-md-6 d-flex align-items-center">
                  <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/projects/_navbar.html.erb
<div class="container pt-5">
  <div class="row justify-content-between">
    <div class="col">
      <%= link_to root_path, class:"navbar-brand"  do %>
        <b style="font-family: bankgothic; font-weight: 900; font-size: 35px; width: 300px;">BURKUT</b>
        <b style="font-family: bankgothic; font-weight: 900; font-size: 25px; width: 300px;"><span><%= @type.upcase %>.</span></b>
      <% end %>
    </div>
    <div class="col d-flex justify-content-end">
      <div class="social-media">
        <p class="mb-0 d-flex">
          <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-facebook"><i class="sr-only">Facebook</i></span></a>
          <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-twitter"><i class="sr-only">Twitter</i></span></a>
          <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-instagram"><i class="sr-only">Instagram</i></span></a>
          <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-dribbble"><i class="sr-only">Dribbble</i></span></a>
        </p>
      </div>
    </div>
  </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light sticky-top" id="ftco-navbar">
  <div class="container">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="fa fa-bars"></span> Menu
    </button>
    <form action="#" class="searchform order-lg-last">
      <div class="form-group d-flex">
        <input type="text" class="form-control pl-3" placeholder="Search">
        <button type="submit" placeholder="" class="form-control search"><span class="fa fa-search"></span></button>
      </div>
    </form>
    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item "><%= link_to t('navbar.home').upcase, root_path, class:"nav-link"%></li>
        <li class="nav-item active "><%= link_to t('navbar.project').upcase, projects_path, class:"nav-link"%></li>
        <li class="nav-item"><a href="team.html" class="nav-link">Our team</a></li>
        <li class="nav-item"><a href="project.html" class="nav-link">Project</a></li>
        <li class="nav-item"><a href="blog.html" class="nav-link">Blog</a></li>
        <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
      </ul>
    </div>
  </div>
</nav>